### ISSUE TITLE
Pulling flow responses in addition to unsolicited messages

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/casepro#14] opened 2016-01-19 08:52 UTC
Want to start a discussion here about what messages should be pulled from RapidPro in addition to unsolicited messages. Any country experience to share? How to determine open-ended?

**Comment by carymc** [comment] 2016-01-19 09:23
Great idea!

I'm happy to chime in here from the U-Report Uganda perspective...

From our experience, even when we ask a Yes or a No question, we always get a sizeable percentage of respondents who provide a lot more information in their reply.  For example, the current flow highlighted on our homepage asks "is conflict affecting your everyday life?"  While we got a lot of Y's and N's, we also got a lot of really interesting information about how conflict could be stopping people from fetching water, going to school, going to the health centre, etc.  These messages would be extremely valuable to partners for programme planning or advocacy, but it's always difficult to get them this information.  Since they'll now be labeled and appearing in U-Partners, this will be much easier.  

Is this the plan though?  Is there a way to easily differentiate between the Y/N or A/B/C/D type of answers, and those have more interesting/important information in them?  Even when we set a flow to be a Yes or No flow (to make sure that the analysis comes out correctly), we'll still a sizeable portion of respondents adding in extra thoughts - so I'm not sure that it's as easy as simply saying that the responses to "open-ended" flows should be the ones that are brought over.

What's the thinking been so far?

**Comment by rowanseymour** [comment] 2016-01-19 09:36
The difficulty is that contacts don't always know that they're responding to a poll question because they may not recall that they are in a flow, or want to be in a flow. So I don't think it's reliable to look at the question being posed in the flow, to determine if the response is something that needs review in Upartners.

I wonder if we should filter messages by other criteria besides keywords to determine whether they should be labelled in UPartners. For example, we can be fairly certain that one word answers don't belong in UPartners as they are almost certainly answers to questions in a flow.

What that would help is avoid is a situation like where a user defines a keyword label "hiv", then a poll goes out asking a question to which "HIV" is a valid answer, and we end up unhelpfully labelling thousands of one word messages with "HIV".

**Comment by carymc** [comment] 2016-01-19 09:51
To be honest, we've had that happen before, and the partners don't mind at
all.  Here in Uganda at least, our partners are used to using the
dashboards to both 1) monitor the general public perception around their
sector, and 2) respond directly to U-Reporters' questions.  I can imagine
that it might be different for an implementation like Zambia's though,
where they are really focusing just on the actual counseling part, as
thousands of "HIV" flow responses could make it difficult to see the real
questions coming in.

I think that you're on to something though when you're thinking about the
number of words.  The one word answers are basically the same thing as Yes
or No, and not really helpful at all.  That information could be seen from
a flow report in RapidPro, assuming that the team downloads it and sends it
to the partner.

The only other thing I was thinking about was whether it would make sense
to have a global setting of some sort to specify whether messages should be
copied over, or even an option within a flow about whether the responses
should be excluded from being copied to U-Partners?  Then a CO could have
more control over it, depending on how they are using the system.  So if
they were going to send out a flow where HIV was a possible answer, then
they could make sure to exclude the replies to this flow from being copied
over.

I can think of pros and cons to that though, so it would probably need a
lot more thought first.

**Comment by rowanseymour** [comment] 2016-01-19 11:40
That's interesting about the Uganda dashboard usage, and makes me wonder what other COs see CasePro as. From the original requirements (which I think were primarily based on Nigeria input) we've always viewed CasePro as akin to a help desk system - with design assumptions like:

* Everything message appears in CasePro should eventually be acted on (whether that's creating a case or just dismissing it)
* We should reduce as much as possible the noise (i.e. messages that clearly aren't requests for help).

Are those assumptions applicable to COs like Uganda?

**Comment by carymc** [comment] 2016-01-19 12:29
I would say that those are the correct assumptions 50% of the time,
specifically for those dashboards where the partner is supporting the
functions of a helpdesk.  We have a couple of partners in Uganda who do
this (especially for HIV, sexual reproductive health questions, and legal
issues), but we also have partners who perform other functions.  .

The other 50% of the time is more focused on partner engagement - allowing
them direct visibility into what their members are thinking and doing, or
what the general citizen population believes about the sector that they
work in (ie. what are citizens directly saying in their own words, instead
of what official reports, surveys, and top-down policies stipulating).

This was actually one of the initial requirement behind the development of
the partner dashboards in RapidSMS.  At first, we realized that we would be
receiving messages where someone needed to provide direct support
(especially for cases of violence), and specific CSOs with trained social
workers with years of experience in this area are much better than U-Report
managers at this.  This is where the set of requirements for helpdesk work
comes from.

The other idea though was that a specific organization (such as the Scouts)
would tap into their grass-roots network to recruit members onto U-Report
(which is beneficial to U-Report as a programme as it adds to the size of
the system and the variety of voices that we can reach), and that the
benefit to the organization would be to use U-Report as it's own
communication tool.  This meant that the responses specifically from the
members that they recruited would be available to them, and they could use
this information to inform their own programme planning and advocacy work
(ie. it could tell them whether their programs were meeting the needs of
their members).  Eventually, we'd also like these partners to be able to
converse more freely with their members as well, although this is very
dependent on cost in an SMS setting like Uganda.

This set of requirements is related to the other upcoming deliverables.  We
need to be able to provide this value to the partner organizations (because
it's been sometimes difficult to do in the past), help them to become more
active with their members, and ensure that U-Reporters voices are being
used to influence programming and advocacy.

The other piece of functionality to keep in mind that's related to this is
the security settings around who can access RapidPro itself vs
U-Partners/CasePro.  Essentially, we've been keeping the number of people
who can login to RapidPro to a minimum (basically just those who create and
send flows), and then allowing partners to access the U-Partners
dashboards.  These dashboards are simpler to use, and they are also
currently the only way to limit the messages viewed to a specific group.
Creating a Viewer or Surveyor in RapidPro allows access to all flows and
responses, which is much more information than most partners need.

**Comment by rowanseymour** [comment] 2016-01-19 13:46
Apologies to @citizenrich for taking this thread off course but this is important feedback to hear - especially just as we're starting a major refactor of the codebase. It does make me think that maybe some of what users expect from CasePro might be best served by other dashboards. I suppose per-country expectations depend largely on what systems CasePro may be replacing.

My concern is that it is difficult to make a dashboard which is a great helpdesk tool, and *also* a great tool for improving partner engagement. The latter sounds like it overlaps considerably with TracPro where partners can see aggregate visualisations of the data from contacts under their remit, and can initiate their own polls with those contacts, etc.

**Comment by carymc** [comment] 2016-01-19 14:54
@rowanseymour, if you'd like to start any new threads to explore any of
these ideas further, please feel free.  I'm happy to provide inputs
wherever, and others will also.  As you said, it's just important that
there's an understanding of all of the requirements and expectations,
because different implementations in different countries will use these
dashboards in different ways.

It's very possible that a lot of the requirements for the partner
engagement piece can be addressed in alternative ways.  And if so, as long
as they are addressed pretty comprehensively, that would be great as well.
These requirements are really at the core of U-Report, as they address two
of our global priorities - 1) provides value to the partner organizations,
which, since they are key to recruitment, ensures that the number of
U-Reporters keeps growing, and 2) uses U-Reporter feedback to influence
programme delivery closest to the ground, which will allow U-Reporters to
see the value of their feedback and keep them engaged for the long-run.

**Comment by rowanseymour** [comment] 2016-05-12 09:35
Flow messages now included since refactor work

**Closed by rowanseymour** 2016-05-12 09:35 UTC
